.PHONY: clean All

All:
	@echo "----------Building project:[ gltfpack - Debug ]----------"
	@cd "gltfpack" && "$(MAKE)" -f  "gltfpack.mk"
clean:
	@echo "----------Cleaning project:[ gltfpack - Debug ]----------"
	@cd "gltfpack" && "$(MAKE)" -f  "gltfpack.mk" clean
